name: Tim Goodchild
favicon: null
layout_spectrum: 0.8661832748912275
typography_spectrum: 0.4837732412852347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#21201e'
    - '#aeaeb0'
    - '#4f4f4f'
    - '#177b76'
    - '#18a79f'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
